### ISSUE TITLE
Swift 3 branch

### ISSUE THREAD

**Issue by lfarah** [hyperoslo/SwiftSnippets#1]
Hey @hyperoslo, I'd be cool to add a Swift 3 branch so we could make the necessary changes over there since a lot of methods changed, like the `dispatch_async`, for example.

**Comment by onmyway133** [comment]
@lfarah Hi, sorry for the delay 😓 
I've just updated it to Swift 3. So any PR towards `master` should be welcome

**Comment by lfarah** [comment]
Awesome! 🎉
